name: Go Test

on:
  push:
    branches:
      - main
    paths:
      - "**/*.go"
  pull_request:
    branches:
      - main
    paths:
      - "**/*.go"

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.21

      - name: Install Dependencies
        run: go mod download

      - name: Run Tests
        run: go test ./...
